language: cpp

os: osx
osx_image: xcode8
compiler:
  - clang

before_install:
  - ./ci/install_deps_osx.sh

cache:
  ccache: true
  directories:
    - $HOME/Library/Caches/Homebrew

stages:
  - build

jobs:
  include:
    - stage:  build
      script: ./build.py
